# This file was generated by GoReleaser. DO NOT EDIT.
cask "torrnado" do
  version "0.5.8"

  on_macos do
    on_arm do
      sha256 "d942ba944ebdc903c85a851f506d5fce6936a54e34a6b2365d154a94c9dd688f"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bcfc8b251346dcf24bcdc5d5f80cf403528ac5587afd1b02a7b786075e46c641"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "5c3d2c413c11cbb0ab7316a6cbb7f9424550b90b8aa611873d39e9c9edbabd54"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e18297a0807a65caf5ad66d2864a2da24d36f3af4729d48086b3cc22e4dbdc60"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_linux_amd64.tar.gz"
    end
  end

  name "torrnado"
  desc "Terminal BitTorrent client with a vim-like interface and a background daemon"
  homepage "https://torrnado.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "torrnado"
  manpage "torrnado.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/torrnado"]
    end
  end

  # No zap stanza required
end
