# This file was generated by GoReleaser. DO NOT EDIT.
cask "torrnado" do
  version "0.6.1"

  on_macos do
    on_arm do
      sha256 "e928e5949c4782d496ee299c37eb7f8713c07c057d9c33df8d77c3a29e76d89b"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "bcfd8cab5aca8ae8e44d19fd20debe01349fcac7b732ca5332a989522bf1f77a"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f33dd1221769accb0d032be2306c030b5b61475d3cbcb6f3ff4b28805c999f68"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "40cdba99e7d5c06ec1814460d64507673fcf91542abff2cd97ed0a86f84a25f2"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_linux_amd64.tar.gz"
    end
  end

  name "torrnado"
  desc "Terminal BitTorrent client with a vim-like interface and a background daemon"
  homepage "https://torrnado.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "torrnado"
  manpage "torrnado.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/torrnado"]
    end
  end

  # No zap stanza required
end
