# This file was generated by GoReleaser. DO NOT EDIT.
cask "torrnado" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/torrnado"]
    end
  end

  version "0.8.2"

  on_macos do
    on_arm do
      sha256 "8e64a7bec311a686c38c2365e5dc0916abe04fd6a14d3bb11d045f92728d4f87"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d00061e31c550f903c0fef47da1ee9bb8d6577223e1902030f3e1b1bb3af34d"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9b684c71e32dd57b57ff5487eb0c56652f2f1d04506601ece330e5704ad2237f"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "efb11b682fc8c79234c1cc14f405738db4351ca3da5ba184b523d1276e8e9d94"
      url "https://github.com/lestex/torrnado/releases/download/v#{version}/torrnado_#{version}_linux_amd64.tar.gz"
    end
  end

  name "torrnado"
  desc "Terminal BitTorrent client with a vim-like interface and a background daemon"
  homepage "https://torrnado.dev/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "torrnado"
  manpage "torrnado.1"

  zap trash: [
      "~/.config/torrnado",
      "~/.local/share/torrnado",
    ]

  caveats <<~EOS
    torrnado runs a background daemon that outlives the TUI. Run
      torrnado stop
    before `brew uninstall` or `brew upgrade`, or the old daemon keeps
    running from the removed binary. `brew uninstall --zap` also removes
    ~/.config/torrnado and ~/.local/share/torrnado.
  EOS
end
